### ISSUE TITLE
change numpy array flags

### ISSUE THREAD

**Issue by qqueing** [lebedov/msgpack-numpy#49]
```
x = np.eye(10)
x.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
y = msgpack.loads(msgpack.dumps(x))
y.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
```
flags are changed, such as "writeable"

**Comment by lebedov** [comment]
When deserializing a serialized array, msgpack_numpy creates a new array from a buffer containing the serialized data. Since  this array doesn't own its memory, OWNDATA and WRITEABLE are False. msgpack_numpy doesn't copy the deserialized array to avoid overhead in those applications for which read-only access is sufficient, but you can obviously copy it yourself.
